(1, 'La solitudine dei numeri primi', 'Paolo Giordano', 2008, 'Romanzo'),
(2, 'Il nome della rosa', 'Umberto Eco', 1980, 'Mistero'),
(3, 'Il Piccolo Principe', 'Antoine de Saint-Exupéry', 1943, 'Fiaba'),
(4, '1984', 'George Orwell', 1949, 'Distopia'),
(5, 'Il grande Gatsby', 'F. Scott Fitzgerald', 1925, 'Romanzo'),
(6, 'Moby Dick', 'Herman Melville', 1851, 'Avventura'),
(7, 'Guerra e pace', 'Lev Tolstoj', 1869, 'Storico'),
(8, 'Il Signore degli Anelli', 'J.R.R. Tolkien', 1954, 'Fantasy'),
(9, 'Il cacciatore di aquiloni', 'Khaled Hosseini', 2003, 'Romanzo'),
(10, 'Orgoglio e pregiudizio', 'Jane Austen', 1813, 'Romantico'),
(11, 'Harry Potter e la pietra filosofale', 'J.K. Rowling', 1997, 'Fantasy'),
(12, 'L\'ombra del vento', 'Carlos Ruiz Zafón', 2001, 'Mistero'),
(13, 'Il buio oltre la siepe', 'Harper Lee', 1960, 'Romanzo'),
(14, 'Il codice Da Vinci', 'Dan Brown', 2003, 'Thriller'),
(15, 'Frankenstein', 'Mary Shelley', 1818, 'Horror'),
(16, 'Lo Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasy'),
(17, 'La fattoria degli animali', 'George Orwell', 1945, 'Satira'),
(18, 'La Divina Commedia', 'Dante Alighieri', 1320, 'Poesia'),
(19, 'I miserabili', 'Victor Hugo', 1862, 'Storico'),
(20, 'Don Chisciotte', 'Miguel de Cervantes', 1605, 'Romanzo'),
(21, 'Gita al faro', 'Virginia Woolf', 1927, 'Romanzo modernista'),
(22, 'Ulisse', 'James Joyce', 1922, 'Modernismo'),
(23, 'Madame Bovary', 'Gustave Flaubert', 1857, 'Realismo'),
(24, 'Cento anni di solitudine', 'Gabriel García Márquez', 1967, 'Realismo magico'),
(25, 'Crime e Castigo', 'Fëdor Dostoevskij', 1866, 'Psicologico'),
(26, 'Anna Karenina', 'Lev Tolstoj', 1877, 'Romanzo'),
(27, 'L\'insostenibile leggerezza dell\'essere', 'Milan Kundera', 1984, 'Filosofico'),
(28, 'Il processo', 'Franz Kafka', 1925, 'Filosofico'),
(29, 'Il vecchio e il mare', 'Ernest Hemingway', 1952, 'Novelette'),
(30, 'Il Gattopardo', 'Giuseppe Tomasi di Lampedusa', 1958, 'Storico'),
(31, 'I fratelli Karamazov', 'Fëdor Dostoevskij', 1880, 'Filosofico'),
(32, 'A caccia dell’Ottobre Rosso', 'Tom Clancy', 1984, 'Thriller'),
(33, 'Siddhartha', 'Hermann Hesse', 1922, 'Filosofico'),
(34, 'Il guardiano tra il centeno', 'J.D. Salinger', 1951, 'Romanzo'),
(35, 'Fahrenheit 451', 'Ray Bradbury', 1953, 'Distopia'),
(36, 'Il diario di Anna Frank', 'Anne Frank', 1947, 'Biografia'),
(37, 'La campana di vetro', 'Sylvia Plath', 1963, 'Romanzo'),
(38, 'Le avventure di Huckleberry Finn', 'Mark Twain', 1884, 'Avventura'),
(39, 'Al faro', 'Virginia Woolf', 1927, 'Modernismo'),
(40, 'La strada', 'Cormac McCarthy', 2006, 'Apocalittico'),
(41, 'La metamorfosi', 'Franz Kafka', 1915, 'Novella'),
(42, 'Invisible Man', 'Ralph Ellison', 1952, 'Sociale'),
(43, 'Beloved', 'Toni Morrison', 1987, 'Storico'),
(44, 'La morte di Ivan Ilijč', 'Lev Tolstoj', 1886, 'Classico'),
(45, 'Solaris', 'Stanisław Lem', 1961, 'Sci-fi'),
(46, 'Neuromancer', 'William Gibson', 1984, 'Cyberpunk'),
(47, 'Il signore delle mosche', 'William Golding', 1954, 'Allegoria'),
(48, 'Il Silmarillion', 'J.R.R. Tolkien', 1977, 'Fantasy'),
(49, 'Blade Runner', 'Philip K. Dick', 1968, 'Sci-fi'),
(50, 'Il deserto dei Tartari', 'Dino Buzzati', 1940, 'Romanzo');
